# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: packflow_dev
  username: nulogy
  password: Nulogy4Ever
  host: localhost

test:
  adapter: postgresql
  database: packflow_test
  username: nulogy
  password: Nulogy4Ever
  host: localhost
